tokenizer: "sberbank-ai/rugpt3small_based_on_gpt2"
model: "sberbank-ai/rugpt3small_based_on_gpt2"
seed: 65537

dataset:
  path: "data/questions.txt"
  train_size: 0.98
  train_batch_size: 2
  val_batch_size: 2
  limit_batches: 0.01


training:
  n_gpus: 0
  output_dir: "training_output/"
  save_model_dir: "training_output/model/"

  opt:
    lr: 2e-5
    w_decay: 0.01
    max_epochs: 1
    warmup_steps: 0.1
    grad_accumulation_steps: 1
    grad_clip: 1

  logging:
    val_check_interval: 4
    save_top_k: 1
    log_steps: 100

hydra:
  run:
    dir: training_output_data/${now:%Y-%m-%d}/${now:%H-%M-%S}
output:
  logger_dir: training_output_data/