tokenizer: "sberbank-ai/rugpt3small_based_on_gpt2"
model: "sberbank-ai/rugpt3small_based_on_gpt2"
seed: 65537

dataset:
  path: "data/questions_filtered.txt"
  train_size: 0.9
  train_batch_size: 3
  val_batch_size: 3
  limit_batches: 1.0
  seq_len: 350


training:
  n_gpus: 1
  output_dir: "training_output/"
  save_model_dir: "training_output/model/"

  opt:
    lr: 1e-6
    w_decay: 0.05
    eps: 1e-8
    max_epochs: 2
    warmup_steps: 0.05
    grad_accumulation_steps: 1
    grad_clip: 0

  logging:
    val_check_interval: 0.1
    save_top_k: 2
    log_steps: 100

hydra:
  run:
    dir: training_output_data/${now:%Y-%m-%d}/${now:%H-%M-%S}
output:
  logger_dir: training_output_data/