tokenizer: "sberbank-ai/rugpt3small_based_on_gpt2"
model: "sberbank-ai/rugpt3small_based_on_gpt2"
seed: 65537

dataset:
  path: "data/questions_small.txt"
  # path: "data/questions.txt"
  train_size: 0.15
  train_batch_size: 2
  val_batch_size: 2


training:
  n_gpus: 0
  output_dir: "training_output/"
  save_model_dir: "training_output/model/"

  params:
    lr: 2e-5
    w_decay: 0.01
    max_epochs: 3
    warmup_steps: 200

  logging:
    val_check_interval: 0.1

    log_steps: 100
    eval_steps: 60
    save_models: 1

hydra:
  output_subdir: null
